In [1]:
import torch


In [2]:
torch.version.__version__

'2.3.1'

In [3]:
torch.cuda.is_available()

True

In [3]:
torch.cuda.device_count()

1

In [4]:
torch.cuda.get_device_properties(0)

_CudaDeviceProperties(name='NVIDIA GeForce RTX 3060 Laptop GPU', major=8, minor=6, total_memory=6143MB, multi_processor_count=30)

In [5]:
if torch.cuda.is_available():
    print("GPU is available")
    num_gpus = torch.cuda.device_count()
    print(f"Number of available GPUs: {num_gpus}")

    for i in range(num_gpus):
        gpu_props = torch.cuda.get_device_properties(i)
        print(f"GPU {i}:")
        print(f"  Name: {gpu_props.name}")
        print(f"  Total memory: {gpu_props.total_memory / (1024 * 1024)} MB")
        print(f"  Compute capability: {gpu_props.major}.{gpu_props.minor}")
else:
    print("GPU is not available")

GPU is available
Number of available GPUs: 1
GPU 0:
  Name: NVIDIA GeForce RTX 3060 Laptop GPU
  Total memory: 6143.5 MB
  Compute capability: 8.6


In [7]:
a = torch.ones(3,3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [8]:
b = torch.ones(3,3)

In [9]:
a + b 

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [10]:
torch.cuda.is_available()

True

In [11]:
a = a.to('cuda')
b = b.to('cuda')
a + b

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], device='cuda:0')

In [12]:
a = a.to('cpu')

In [3]:
a = torch.ones(3,3)

In [4]:
b = torch.ones(3,3)

In [5]:
a + b

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [6]:
a = a.to('cuda')
b = b.to('cuda')
a + b

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], device='cuda:0')