In [1]:
import torch

In [2]:
img_t = torch.randn(3, 5, 5)  # shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [5]:
print(img_t)

tensor([[[ 0.0869, -0.9562,  0.5911,  0.2382,  1.1126],
         [-1.4486, -0.4550,  1.8754, -0.9998, -0.0129],
         [-0.5538,  0.4646,  0.4087, -1.0016, -0.9715],
         [ 0.2246,  0.9119, -0.3628, -1.0283,  0.2119],
         [-0.6576,  0.6554,  0.7890,  0.2821, -0.5278]],

        [[ 1.0571, -0.6122, -0.5944,  0.9636, -0.1630],
         [ 0.2059,  1.2749,  1.3276,  0.9712,  1.0257],
         [ 1.1284,  0.6138,  1.5142,  0.5984,  0.9266],
         [-1.0952, -1.8674,  0.9860,  0.1952, -0.5101],
         [-0.2508,  1.5445, -0.9211,  1.0383, -0.1872]],

        [[-0.6052, -0.3879, -0.4899, -0.1551,  1.0497],
         [-0.2572,  0.4232, -0.6105, -0.7864,  0.0947],
         [ 1.0499,  1.3242, -0.3187,  1.4906,  0.2694],
         [ 0.3136, -0.7626,  0.0042, -0.2540, -1.6652],
         [ 0.5921, -0.4410,  0.6714, -0.1353,  0.6119]]])


In [6]:
batch_t = torch.randn(2, 3, 5, 5)  # shape [batch, channels, rows, columns]
batch_t

tensor([[[[-7.6417e-01, -2.0371e+00, -1.0506e+00,  3.1299e-01, -6.1085e-01],
          [-5.1051e-02,  1.9981e-01,  3.0125e-01,  1.1571e+00, -7.1473e-02],
          [ 1.3148e+00,  1.2980e+00,  2.9347e-02, -1.3969e+00,  2.2190e-01],
          [-7.6489e-01,  8.4538e-01, -2.4829e-01,  1.0132e+00, -8.4737e-01],
          [-1.3613e+00,  1.9013e+00,  1.3661e-01, -1.3891e+00,  1.5891e-01]],

         [[-4.7915e-01,  1.2596e+00,  7.9482e-02,  7.5660e-01, -1.0671e+00],
          [ 5.3922e-01,  7.6401e-01,  2.8260e+00, -1.4844e+00,  2.0199e-01],
          [-8.0772e-01, -1.4622e-01,  1.7712e-01,  6.9754e-01, -3.1827e-01],
          [ 1.8810e+00, -1.0554e+00,  3.9331e-01,  1.0228e+00, -4.1355e-01],
          [ 1.6816e-01,  2.1946e-03, -2.8268e+00, -3.8403e-01, -1.1552e+00]],

         [[ 4.9409e-01,  2.2540e+00,  4.7040e-01, -5.9877e-01,  6.8104e-01],
          [ 5.0014e-01,  1.3215e-01, -4.0945e-01,  4.3848e-01,  1.3367e+00],
          [-8.4992e-01,  4.9217e-01,  3.6789e-01, -1.0274e+00, -1.2600e+

In [11]:
# Generate a tensor of size (3, 5, 5) with values stored in natural number sequence
img_t = torch.arange(75).reshape(3, 5, 5)

img_t = img_t.float()
img_t

tensor([[[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.],
         [20., 21., 22., 23., 24.]],

        [[25., 26., 27., 28., 29.],
         [30., 31., 32., 33., 34.],
         [35., 36., 37., 38., 39.],
         [40., 41., 42., 43., 44.],
         [45., 46., 47., 48., 49.]],

        [[50., 51., 52., 53., 54.],
         [55., 56., 57., 58., 59.],
         [60., 61., 62., 63., 64.],
         [65., 66., 67., 68., 69.],
         [70., 71., 72., 73., 74.]]])

In [13]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
print(img_gray_naive.shape, batch_gray_naive.shape)

torch.Size([5, 5]) torch.Size([2, 5, 5])


In [14]:
img_gray_naive

tensor([[25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34.],
        [35., 36., 37., 38., 39.],
        [40., 41., 42., 43., 44.],
        [45., 46., 47., 48., 49.]])

In [15]:
weights.shape

torch.Size([3])

In [18]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
unsqueezed_weights.shape, unsqueezed_weights, weights

(torch.Size([3, 1, 1]),
 tensor([[[0.2126]],
 
         [[0.7152]],
 
         [[0.0722]]]),
 tensor([0.2126, 0.7152, 0.0722]))

In [19]:
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_weights.shape, batch_weights.shape

(torch.Size([3, 5, 5]), torch.Size([2, 3, 5, 5]))