In [1]:
import torch

In [2]:
t = torch.tensor(list(range(9)))
t, t.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]), torch.Size([9]))

In [3]:
t.size(), t.storage_offset(), t.stride()

(torch.Size([9]), 0, (1,))

In [4]:
b = t.view(3, 3)
b, b.shape

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 torch.Size([3, 3]))

- 在notebook里，如果在不同的单元格查看b和t的id(storage())，二者的结果是不同的
- 但是如果在同一个单元格里运行，则二者的id相同
- 但是==的结果应为False

好吧，上面的结论完全是错误的，实际上结果是随机，有时候二者相同，有时候又不相同...

In [59]:
id(t.storage()), id(b.storage())

(2029486399056, 2029486399056)

In [45]:
x = id(t.storage())
y = id(b.storage())
x, y, x == y

(2031271926272, 2031271926272, True)

In [19]:
id(t.storage())

2029479393472

In [20]:
id(b.storage())

2029485996560

很可能是因为tensor.storage()已经被废弃了，而导致二者的类存在不同。
如果使用推荐的untyped_storage()则不会出现这种问题。
也可以使用

In [7]:
t.untyped_storage() == b.untyped_storage()

True

In [8]:
c = b[1:, 1:]
c, c.shape, c.size(), c.storage_offset(), c.stride()

(tensor([[4, 5],
         [7, 8]]),
 torch.Size([2, 2]),
 torch.Size([2, 2]),
 4,
 (3, 1))

In [61]:
b[1, 1] = 99
t, b

(tensor([ 0,  1,  2,  3, 99,  5,  6,  7,  8]),
 tensor([[ 0,  1,  2],
         [ 3, 99,  5],
         [ 6,  7,  8]]))

# 2

In [78]:
a = torch.tensor(list(range(9)))

In [79]:
a.dtype

torch.int64

In [80]:
b = torch.cos(a)
b, b.dtype

(tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
         -0.1455]),
 torch.float32)

In [81]:
c = torch.sqrt(a)
c, c.dtype

(tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284]),
 torch.float32)

看样子，to(float)和float()还是不一样的，这里从int64类型开始转换，前者会转换为float64, 而后者会转换为float32.

In [85]:
a = a.to(float)
a

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64)

In [70]:
a = a.float()
a.dtype

torch.float32

但是，使用to(torch.float)就也会转换为float32...暂时还不太理解为什么...

In [87]:
a = torch.tensor(list(range(9)))
a.dtype

torch.int64

a = a.to(torch.float)
a.dtype