In [3]:
a = [1.0, 2.0, 1.0]
a[0]

1.0

In [4]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [5]:
import torch

In [6]:
a = torch.ones(3)

In [7]:
a[2]

tensor(1.)

In [8]:
float(a[2])

1.0

In [9]:
a[2] = 2.0

In [10]:
a

tensor([1., 1., 2.])

In [11]:
a[2]

tensor(2.)

In [12]:
points = torch.zeros(6)

In [13]:
points[0]=4.0
points[1]=1.0
points[2]=5.0 
points[3]=3.0
points[4]=2.0
points[5]=1.0

In [14]:
points

tensor([4., 1., 5., 3., 2., 1.])

In [15]:
points = torch.tensor([[4.0, 1.0],[5.0, 3.0],[2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [16]:
points.shape

torch.Size([3, 2])

In [17]:
points[0, 0]

tensor(4.)

In [18]:
points[1, 1]

tensor(3.)

In [19]:
points.storage()

C:\Users\LibraJiang\AppData\Local\Temp\ipykernel_1796\2396954748.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [20]:
points.untyped_storage()

 0
 0
 128
 64
 0
 0
 128
 63
 0
 0
 160
 64
 0
 0
 64
 64
 0
 0
 0
 64
 0
 0
 128
 63
[torch.storage.UntypedStorage(device=cpu) of size 24]

In [21]:
second_points = points[1]
second_points

tensor([5., 3.])

In [22]:
second_points.storage_offset()

2

In [23]:
second_points.size(), second_points.shape

(torch.Size([2]), torch.Size([2]))

In [24]:
second_points[0] = 10.0
second_points

tensor([10.,  3.])

In [25]:
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [26]:
another_points = points[1].clone()
another_points.storage_offset()

0

In [27]:
another_points[0] = 100.0
another_points

tensor([100.,   3.])

In [28]:
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [29]:
second_points.stride()

(1,)

In [30]:
points.stride()

(2, 1)

In [31]:
points_t = points.t()
points_t

tensor([[ 4., 10.,  2.],
        [ 1.,  3.,  1.]])

可以看到这里，points和其转置的storage()的id是不一样的，而书中所给的答案应该是一样，并且使用untyped_storage()给出的二者的id也是一样的，所以应该是现在的pytorch版本中的storage()做了一些改动。

In [32]:
id(points.storage()) == id(points_t.storage()) 

False

In [33]:
points.storage() == points_t.storage()

False

In [34]:
id(points.untyped_storage()) == id(points_t.untyped_storage())

True

但是这里也可以看到，二者的首个元素的内存地址是一样的。而id()只是表示两个类(Storage类)的id。也就是说，现在tensor和tensor.t()的存储内容和存储地址不变，但其对应的Storage()类是不一样的了。而untyped_storage()的返回值还是一样的。

In [35]:
points.storage().data_ptr()

4614430786112

In [36]:
points_t.storage().data_ptr()

4614430786112

In [37]:
points_t.stride()

(1, 2)

In [43]:
points.storage()

 4.0
 1.0
 10.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [44]:
points_t.storage()

 4.0
 1.0
 10.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [49]:
some_t = torch.ones(3, 4, 5)
some_t.stride()

(20, 5, 1)

转置操作t()只能作用于二维及以下的张量

In [ ]:
some_t_t = some_t.t()
some_t_t.stride()

In [53]:
transpose_t = some_t.transpose(0, 2)
transpose_t.shape, transpose_t.stride()


(torch.Size([5, 4, 3]), (1, 5, 20))

In [54]:
points.is_contiguous(), points_t.is_contiguous()

(True, False)