In [3]:
import torch

In [5]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [6]:
double_points.dtype, short_points.dtype

(torch.float64, torch.int16)

In [7]:
double_points 

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

以dtype命名的这些类型转换函数，如double()本质都是to(dtype)函数的简写，to()函数才是更常见的用法。

In [8]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [9]:
short_points

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)

In [10]:
double_points = torch.zeros(10,2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [11]:
double_points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

to()函数不是inplace函数

In [14]:
double_points = double_points.to(dtype=torch.float)
double_points.dtype

torch.float32

In [15]:
points_64 = torch.rand(5, dtype=torch.double)
points_64

tensor([0.1515, 0.0966, 0.6769, 0.6227, 0.1336], dtype=torch.float64)

In [16]:
points_short = points_64.to(torch.short)
points_short

tensor([0, 0, 0, 0, 0], dtype=torch.int16)

In [17]:
a = torch.tensor(12.3)
a.to(torch.short)

tensor(12, dtype=torch.int16)

In [18]:
a.to(torch.int)

tensor(12, dtype=torch.int32)

运算时会将不同类型的数据都先往最大类型转换，转换失败应该就会直接报错

In [19]:
out = points_64 * points_short

In [20]:
out

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)