In [6]:
import torch

In [1]:
some_list = list(range(6))
some_list

[0, 1, 2, 3, 4, 5]

In [2]:
some_list[:4]

[0, 1, 2, 3]

In [3]:
some_list[:-1]

[0, 1, 2, 3, 4]

In [4]:
some_list[1:4:2]

[1, 3]

In [7]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [8]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [9]:
points[1:,:]

tensor([[5., 3.],
        [2., 1.]])

In [10]:
points[1:,0]

tensor([5., 2.])

In [14]:
points_t = points.t()
points_t, points_t[:,1:], points_t[:,2:]

(tensor([[4., 5., 2.],
         [1., 3., 1.]]),
 tensor([[5., 2.],
         [3., 1.]]),
 tensor([[2.],
         [1.]]))

In [21]:
points_t[:,1].shape

torch.Size([2])

In [20]:
img = torch.randn(3, 5, 5)
img[:, 1:,1].shape

torch.Size([3, 4])

In [22]:
a = points[None]

In [23]:
a.shape

torch.Size([1, 3, 2])

In [24]:
points_np = points.numpy()
points_np

array([[4., 1.],
       [5., 3.],
       [2., 1.]], dtype=float32)

In [25]:
points_from_np = torch.from_numpy(points_np)
points_from_np

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])