In [2]:
import torch

In [3]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points.shape

torch.Size([3, 2])

In [4]:
torch.save(points, '../../myData/p1ch3/ourpoints.t')

In [5]:
with open('../../myData/p1ch3/ourpoints.t', 'wb') as f:
    torch.save(points, f)

In [6]:
a = torch.load('../../myData/p1ch3/ourpoints.t')
a

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [7]:
with open('../../myData/p1ch3/ourpoints.t', 'rb') as f:
    b = torch.load(f)

In [8]:
b

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [9]:
import h5py

In [10]:
f = h5py.File("../../myData/p1ch3/ourpoints.hdf5", "w")
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [11]:
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [12]:
f = h5py.File('../../myData/p1ch3/ourpoints.hdf5', 'r')
dset = f['coords']
dset

<HDF5 dataset "coords": shape (3, 2), type "<f4">

dset是Dataset类，直接转换为tensor会触发warning，提示这种转换会增加耗时，建议先转换为ndarray类型，再转成tensor，所以视频里给的是torch.tensor(dset[:])，索引操作会触发类型转换；当然也可以用numpy.array(dset)手动转换。

In [16]:
dset.type 

AttributeError: 'Dataset' object has no attribute 'type'

In [17]:
dset[:]

array([[1., 4.],
       [2., 1.],
       [3., 5.]], dtype=float32)

In [19]:
import numpy as np

In [20]:
dset_array = np.array(dset)
dset_array

array([[1., 4.],
       [2., 1.],
       [3., 5.]], dtype=float32)

In [13]:
last_points = dset[-2:]
last_points

array([[2., 1.],
       [3., 5.]], dtype=float32)

In [14]:
points = torch.tensor(dset[:])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [21]:
test = torch.tensor(dset_array)
test 

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [22]:
last_points = torch.from_numpy(dset[-2:])
last_points

tensor([[2., 1.],
        [3., 5.]])

In [23]:
f.close()

在cpu数据和gpu数据之间进行转换

In [30]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])

In [25]:
points_gpu = torch.tensor([[4.0, 1.0],[5.0, 3.0],[2.0, 1.0]], device='cuda')

In [26]:
points + points_gpu

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

与数据类型转换float()类似，cpu和gpu之间切换也可以直接用以设备名命名的方法，如cpu()和cuda()；也可以用更根本的to()方法。

In [35]:
points = points.cpu()
# points = points.to('cuda')
# points = points.cuda()
points = points.to(device='cuda:0') # 可以在GPU上指定设备

In [36]:
points + points_gpu

tensor([[5., 5.],
        [7., 4.],
        [5., 6.]], device='cuda:0')

In [38]:
points = points.to('cpu')

In [39]:
points = 2 * points 
points_gpu = 2 * points.to('cuda')
points_gpu

tensor([[ 4., 16.],
        [ 8.,  4.],
        [12., 20.]], device='cuda:0')

In [40]:
points_gpu = points_gpu + 4
points_gpu

tensor([[ 8., 20.],
        [12.,  8.],
        [16., 24.]], device='cuda:0')