# Autograd 自动计算梯度

In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

torch.set_printoptions(edgeitems=2, threshold=50)

In [12]:
t_c = [0.5, 14.0, 15.0, 28.0, 11.0, 8.0, 3.0, -4.0, 6.0, 13.0, 21.0]
t_u = [35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4]
t_c = torch.tensor(t_c)
t_u = torch.tensor(t_u)

In [13]:
t_un = 0.1 * t_u

In [14]:
def model(x, w, b):
    return w * x + b

In [15]:
def loss_fn(p, y):
    squared_diffs = (p - y) ** 2
    return squared_diffs.mean()

In [16]:
params = torch.tensor([1.0, 0.0], requires_grad=True)

In [18]:
params.grad is None

True

In [19]:
params, params.shape

(tensor([1., 0.], requires_grad=True), torch.Size([2]))

*操作为解包操作，可以将张量展开为所需的参数

In [20]:
loss = loss_fn(model(t_u, *params), t_c)

In [21]:
loss.backward()

In [22]:
params.grad

tensor([4517.2969,   82.6000])

In [23]:
if params.grad is not None:
    params.grad.zero_()

In [24]:
params.grad

tensor([0., 0.])

In [30]:
def training_loop(n_epochs, lr, params, x, y):
    for epoch in range(1, n_epochs + 1):
        if params.grad is not None:
            params.grad.zero_()

        p = model(x, *params)
        loss = loss_fn(p, y)
        loss.backward()

        with torch.no_grad():
            params -= lr * params.grad
        if epoch % 500 == 0:
            print(f"Epoch: {epoch}, Loss: {loss.item():.4f}")
    return params

In [32]:
params = training_loop(
    n_epochs=5000,
    lr=1e-2,
    params=torch.tensor([1.0, 0.0], requires_grad=True),
    x=t_un,
    y=t_c,
)

Epoch: 500, Loss: 7.8601
Epoch: 1000, Loss: 3.8285
Epoch: 1500, Loss: 3.0922
Epoch: 2000, Loss: 2.9577
Epoch: 2500, Loss: 2.9331
Epoch: 3000, Loss: 2.9286
Epoch: 3500, Loss: 2.9278
Epoch: 4000, Loss: 2.9277
Epoch: 4500, Loss: 2.9277
Epoch: 5000, Loss: 2.9276
