In [2]:
import torch

In [13]:
src = torch.Tensor(
    [
        [-1.0276, 0.2673, -1.1752, -0.8823],
        [-0.6447, -0.8256, 0.1542, -0.4242],
        [-0.3413, -0.5314, -0.6573, -0.1154],
    ]
)
src

tensor([[-1.0276,  0.2673, -1.1752, -0.8823],
        [-0.6447, -0.8256,  0.1542, -0.4242],
        [-0.3413, -0.5314, -0.6573, -0.1154]])

In [22]:
index = torch.tensor([[3, 8, 2, 0], [1, 2, 0, 3]])

In [14]:
output = torch.zeros(2, 5)
output = output.scatter(1, index, src)
output

tensor([[-0.8823,  0.2673, -1.1752, -1.0276,  0.0000],
        [ 0.1542, -0.6447, -0.8256, -0.4242,  0.0000]])

In [15]:
output = torch.zeros(4, 2)
output = output.scatter(0, index.t(), src.t())
output

tensor([[-0.8823,  0.1542],
        [ 0.2673, -0.6447],
        [-1.1752, -0.8256],
        [-1.0276, -0.4242]])

In [20]:
index, src

(tensor([[3, 1, 2, 0],
         [1, 2, 0, 3]]),
 tensor([[-1.0276,  0.2673, -1.1752, -0.8823],
         [-0.6447, -0.8256,  0.1542, -0.4242],
         [-0.3413, -0.5314, -0.6573, -0.1154]]))

In [19]:
output = torch.zeros(4, 4)
output = output.scatter(0, index, src)
output

tensor([[ 0.0000,  0.0000,  0.1542, -0.8823],
        [-0.6447,  0.2673,  0.0000,  0.0000],
        [ 0.0000, -0.8256, -1.1752,  0.0000],
        [-1.0276,  0.0000,  0.0000, -0.4242]])

In [25]:
output = torch.zeros(9, 9)
output = output.scatter(1, index.t(), src.t())
output

tensor([[ 0.0000, -0.6447,  0.0000, -1.0276,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000],
        [ 0.0000,  0.0000, -0.8256,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.2673],
        [ 0.1542,  0.0000, -1.1752,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000],
        [-0.8823,  0.0000,  0.0000, -0.4242,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000]])