In [1]:
import torch
import numpy as np

In [2]:
a = np.array([[[1, 2, 3], [2, 2, 2]], [[1, 2, 3], [2, 2, 2]]])
n_1 = np.sum(a, axis=0)
n_2 = np.sum(a, axis=1)
n_3 = np.sum(a, axis=2)

In [3]:
a.shape

(2, 2, 3)

In [4]:
n_1, n_1.shape

(array([[2, 4, 6],
        [4, 4, 4]]),
 (2, 3))

In [5]:
n_2, n_2.shape

(array([[3, 4, 5],
        [3, 4, 5]]),
 (2, 3))

In [6]:
n_3, n_3.shape

(array([[6, 6],
        [6, 6]]),
 (2, 2))

In [7]:
b = torch.from_numpy(a).to(dtype=torch.float32)
n1 = torch.mean(b, dim=0)
n2 = torch.mean(b, dim=1)
n3 = torch.mean(b, dim=2)

In [8]:
n1, n2, n3

(tensor([[1., 2., 3.],
         [2., 2., 2.]]),
 tensor([[1.5000, 2.0000, 2.5000],
         [1.5000, 2.0000, 2.5000]]),
 tensor([[2., 2.],
         [2., 2.]]))

In [10]:
import torch.nn as nn

In [13]:
y = torch.rand(size=[2, 2, 3])
print(y)
# y的size是2,2,3。可以看成有两张表，每张表2行3列
net_1 = nn.Softmax(dim=0)
net_2 = nn.Softmax(dim=1)
net_3 = nn.Softmax(dim=2)
n1 = net_1(y)
n2 = net_2(y)
n3 = net_3(y)
print("dim=0的结果是：\n", n1, "\n")
print("dim=1的结果是：\n", n2, "\n")
print("dim=2的结果是：\n", n3, "\n")
n1.shape, n2.shape, n3.shape

tensor([[[0.6464, 0.0657, 0.0173],
         [0.8182, 0.7192, 0.7511]],

        [[0.7762, 0.7896, 0.7568],
         [0.8208, 0.2054, 0.1491]]])
dim=0的结果是：
 tensor([[[0.4676, 0.3265, 0.3231],
         [0.4994, 0.6257, 0.6461]],

        [[0.5324, 0.6735, 0.6769],
         [0.5006, 0.3743, 0.3539]]]) 

dim=1的结果是：
 tensor([[[0.4572, 0.3422, 0.3244],
         [0.5428, 0.6578, 0.6756]],

        [[0.4889, 0.6420, 0.6474],
         [0.5111, 0.3580, 0.3526]]]) 

dim=2的结果是：
 tensor([[[0.4779, 0.2674, 0.2548],
         [0.3520, 0.3188, 0.3292]],

        [[0.3340, 0.3385, 0.3275],
         [0.4875, 0.2635, 0.2490]]]) 



(torch.Size([2, 2, 3]), torch.Size([2, 2, 3]), torch.Size([2, 2, 3]))

## 总结：
不论是np中的axis还是torch中的dim，在运算中作为参数，都表示该运算沿着指定的"轴"，也就是维度进行运算，至于在运算后是否会降维，则只与运算本身的规则有关，比如sum()和mean()等运算，本身就是`List -> Num`的运算，运行后自然指定的dim会被消去；而Softmax()这种`List -> List`的运算，则会保留原有维度。