In [2]:
%matplotlib inline
import numpy as np

**不知道为什么这里需要运行一下LunaDataset()，后面才能正常运行**  
不然后面调用vis中的findPositiveSample()时会返回空值，而且再次实例化LunaDataset()时也会为空

In [3]:
from p2ch10.dsets import getCandidateInfoList, getCt, LunaDataset

ds = LunaDataset()
ds.candidateInfo_list

2024-06-28 13:11:07,950 INFO     pid:21668 p2ch10.dsets:187:__init__ <p2ch10.dsets.LunaDataset object at 0x00000286077EF8F0>: 110143 training samples


[CandidateInfoTuple(isNodule_bool=True, diameter_mm=32.27003025, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.287966244644280690737019247886', center_xyz=(67.61451718, 85.02525992, -109.8084416)),
 CandidateInfoTuple(isNodule_bool=True, diameter_mm=25.23320204, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.511347030803753100045216493273', center_xyz=(63.4740118048, 73.9174523314, -213.736128767)),
 CandidateInfoTuple(isNodule_bool=True, diameter_mm=23.35064438, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.179049373636438705059720603192', center_xyz=(57.42, 81.14, -118.09)),
 CandidateInfoTuple(isNodule_bool=True, diameter_mm=23.35064438, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.179049373636438705059720603192', center_xyz=(56.4889724157, 85.9418105037, -115.9731945)),
 CandidateInfoTuple(isNodule_bool=True, diameter_mm=23.35064438, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.179049373636438705059720603192', center_xyz=(50.4361084414, 90.0424445754, -113.908439345)),
 CandidateI

In [4]:
from p2ch10.dsets import getCandidateInfoList, getCt, LunaDataset

candidateInfo_list = getCandidateInfoList(requireOnDisk_bool=False)
positiveInfo_list = [x for x in candidateInfo_list if x[0]]
diameter_list = [x[1] for x in positiveInfo_list]

In [5]:
ds = LunaDataset()
ds.candidateInfo_list

2024-06-28 13:11:13,899 INFO     pid:21668 p2ch10.dsets:187:__init__ <p2ch10.dsets.LunaDataset object at 0x0000028669B9FCE0>: 110143 training samples


[CandidateInfoTuple(isNodule_bool=True, diameter_mm=32.27003025, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.287966244644280690737019247886', center_xyz=(67.61451718, 85.02525992, -109.8084416)),
 CandidateInfoTuple(isNodule_bool=True, diameter_mm=25.23320204, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.511347030803753100045216493273', center_xyz=(63.4740118048, 73.9174523314, -213.736128767)),
 CandidateInfoTuple(isNodule_bool=True, diameter_mm=23.35064438, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.179049373636438705059720603192', center_xyz=(57.42, 81.14, -118.09)),
 CandidateInfoTuple(isNodule_bool=True, diameter_mm=23.35064438, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.179049373636438705059720603192', center_xyz=(56.4889724157, 85.9418105037, -115.9731945)),
 CandidateInfoTuple(isNodule_bool=True, diameter_mm=23.35064438, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.179049373636438705059720603192', center_xyz=(50.4361084414, 90.0424445754, -113.908439345)),
 CandidateI

In [6]:
positiveInfo_list

[CandidateInfoTuple(isNodule_bool=True, diameter_mm=32.27003025, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.287966244644280690737019247886', center_xyz=(67.61451718, 85.02525992, -109.8084416)),
 CandidateInfoTuple(isNodule_bool=True, diameter_mm=30.61040636, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.112740418331256326754121315800', center_xyz=(47.90350511, 37.60442008, -99.93417567)),
 CandidateInfoTuple(isNodule_bool=True, diameter_mm=30.61040636, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.112740418331256326754121315800', center_xyz=(44.19, 37.79, -107.01)),
 CandidateInfoTuple(isNodule_bool=True, diameter_mm=30.61040636, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.112740418331256326754121315800', center_xyz=(40.69, 32.19, -97.15)),
 CandidateInfoTuple(isNodule_bool=True, diameter_mm=27.44242293, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.943403138251347598519939390311', center_xyz=(-45.29440163, 74.86925386, -97.52812481)),
 CandidateInfoTuple(isNodule_bool=True, diam

In [7]:
print(len(positiveInfo_list))
print(positiveInfo_list[0])

1351
CandidateInfoTuple(isNodule_bool=True, diameter_mm=32.27003025, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.287966244644280690737019247886', center_xyz=(67.61451718, 85.02525992, -109.8084416))


In [8]:
for i in range(0, len(diameter_list), 100):
    print("{:4}  {:4.1f} mm".format(i, diameter_list[i]))

   0  32.3 mm
 100  17.7 mm
 200  13.0 mm
 300  10.0 mm
 400   8.2 mm
 500   7.0 mm
 600   6.3 mm
 700   5.7 mm
 800   5.1 mm
 900   4.7 mm
1000   4.0 mm
1100   0.0 mm
1200   0.0 mm
1300   0.0 mm


In [9]:
for candidateInfo_tup in positiveInfo_list:
    if candidateInfo_tup.series_uid.endswith("565"):
        print(candidateInfo_tup)

CandidateInfoTuple(isNodule_bool=True, diameter_mm=0.0, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.124154461048929153767743874565', center_xyz=(146.12, -160.55, -309.93))


In [10]:
for candidateInfo_tup in positiveInfo_list[:10]:
    print(candidateInfo_tup)
for candidateInfo_tup in positiveInfo_list[-10:]:
    print(candidateInfo_tup)

for candidateInfo_tup in positiveInfo_list:
    if candidateInfo_tup.series_uid.endswith("565"):
        print(candidateInfo_tup)

CandidateInfoTuple(isNodule_bool=True, diameter_mm=32.27003025, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.287966244644280690737019247886', center_xyz=(67.61451718, 85.02525992, -109.8084416))
CandidateInfoTuple(isNodule_bool=True, diameter_mm=30.61040636, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.112740418331256326754121315800', center_xyz=(47.90350511, 37.60442008, -99.93417567))
CandidateInfoTuple(isNodule_bool=True, diameter_mm=30.61040636, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.112740418331256326754121315800', center_xyz=(44.19, 37.79, -107.01))
CandidateInfoTuple(isNodule_bool=True, diameter_mm=30.61040636, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.112740418331256326754121315800', center_xyz=(40.69, 32.19, -97.15))
CandidateInfoTuple(isNodule_bool=True, diameter_mm=27.44242293, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.943403138251347598519939390311', center_xyz=(-45.29440163, 74.86925386, -97.52812481))
CandidateInfoTuple(isNodule_bool=True, diameter_mm=27.

In [11]:
np.histogram(diameter_list)

(array([323, 466, 248, 111,  71,  57,  37,  29,   5,   4], dtype=int64),
 array([ 0.        ,  3.22700302,  6.45400605,  9.68100907, 12.9080121 ,
        16.13501512, 19.36201815, 22.58902117, 25.8160242 , 29.04302722,
        32.27003025]))

In [12]:
from p2ch10.vis import findPositiveSamples, showCandidate

positiveSample_list = findPositiveSamples()

2024-06-28 13:11:14,068 INFO     pid:21668 p2ch10.dsets:187:__init__ <p2ch10.dsets.LunaDataset object at 0x000002860780AB10>: 110143 training samples


0 CandidateInfoTuple(isNodule_bool=True, diameter_mm=32.27003025, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.287966244644280690737019247886', center_xyz=(67.61451718, 85.02525992, -109.8084416))
1 CandidateInfoTuple(isNodule_bool=True, diameter_mm=25.23320204, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.511347030803753100045216493273', center_xyz=(63.4740118048, 73.9174523314, -213.736128767))
2 CandidateInfoTuple(isNodule_bool=True, diameter_mm=23.35064438, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.179049373636438705059720603192', center_xyz=(57.42, 81.14, -118.09))
3 CandidateInfoTuple(isNodule_bool=True, diameter_mm=23.35064438, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.179049373636438705059720603192', center_xyz=(56.4889724157, 85.9418105037, -115.9731945))
4 CandidateInfoTuple(isNodule_bool=True, diameter_mm=23.35064438, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.179049373636438705059720603192', center_xyz=(50.4361084414, 90.0424445754, -113.908439345))
5 Candidate

In [13]:
series_uid = positiveSample_list[11][2]
showCandidate(series_uid)

2024-06-28 13:11:14,097 INFO     pid:21668 p2ch10.dsets:187:__init__ <p2ch10.dsets.LunaDataset object at 0x0000028606211B20>: 970 training samples


<IPython.core.display.Javascript object>

1.3.6.1.4.1.14519.5.2.1.6279.6001.752756872840730509471096155114 0 False [0, 1]


In [14]:
series_uid = "1.3.6.1.4.1.14519.5.2.1.6279.6001.124154461048929153767743874565"
showCandidate(series_uid)

2024-06-28 13:11:14,576 INFO     pid:21668 p2ch10.dsets:187:__init__ <p2ch10.dsets.LunaDataset object at 0x0000028615512870>: 1061 training samples


<IPython.core.display.Javascript object>

1.3.6.1.4.1.14519.5.2.1.6279.6001.124154461048929153767743874565 0 False [0]


In [15]:
series_uid = "1.3.6.1.4.1.14519.5.2.1.6279.6001.126264578931778258890371755354"
showCandidate(series_uid)

2024-06-28 13:11:15,142 INFO     pid:21668 p2ch10.dsets:187:__init__ <p2ch10.dsets.LunaDataset object at 0x00000286157B2870>: 605 training samples


<IPython.core.display.Javascript object>

1.3.6.1.4.1.14519.5.2.1.6279.6001.126264578931778258890371755354 0 False [0]


In [16]:
LunaDataset()[0]

2024-06-28 13:11:16,430 INFO     pid:21668 p2ch10.dsets:187:__init__ <p2ch10.dsets.LunaDataset object at 0x000002861181A870>: 110143 training samples


(tensor([[[[-732., -810., -863.,  ..., -848., -865., -890.],
           [-767., -826., -855.,  ..., -908., -896., -879.],
           [-807., -859., -848.,  ..., -898., -903., -897.],
           ...,
           [-874., -869., -839.,  ..., -159., -121., -104.],
           [-923., -930., -911.,  ..., -115., -104., -117.],
           [-898., -898., -901.,  ...,  -89.,  -93., -129.]],
 
          [[-776., -779., -860.,  ..., -852., -875., -874.],
           [-839., -834., -889.,  ..., -875., -894., -898.],
           [-861., -857., -882.,  ..., -838., -865., -889.],
           ...,
           [-862., -932., -917.,  ..., -111.,  -94., -101.],
           [-896., -918., -898.,  ...,  -16.,    1.,  -41.],
           [-875., -894., -881.,  ...,  -55.,  -47.,  -83.]],
 
          [[-854., -898., -884.,  ..., -886., -878., -857.],
           [-856., -876., -865.,  ..., -869., -880., -884.],
           [-841., -859., -881.,  ..., -857., -844., -832.],
           ...,
           [-744., -880., -873.

In [17]:
import numpy as np
import ipyvolume as ipv

V = np.zeros((128, 128, 128))  # our 3d array
# outer box
V[30:-30, 30:-30, 30:-30] = 0.75
V[35:-35, 35:-35, 35:-35] = 0.0
# inner box
V[50:-50, 50:-50, 50:-50] = 0.25
V[55:-55, 55:-55, 55:-55] = 0.0
ipv.quickvolshow(
    V, level=[0.25, 0.75], opacity=0.03, level_width=0.1, data_min=0, data_max=1
)

d:\IDE\Miniforge3\envs\dlwpt\Lib\site-packages\ipyvolume\serialize.py:102: RuntimeWarning: invalid value encountered in cast
  subdata[..., i] = ((gradient[i][zindex] / 2.0 + 0.5) * 255).astype(np.uint8)


Container(children=[VBox(children=(HBox(children=(Label(value='levels:'), FloatSlider(value=0.25, max=1.0, ste…

In [18]:
ct = getCt(series_uid)
ipv.quickvolshow(
    ct.hu_a,
    level=[0.25, 0.5, 0.9],
    opacity=0.1,
    level_width=0.1,
    data_min=-1000,
    data_max=1000,
)

Container(children=[VBox(children=(HBox(children=(Label(value='levels:'), FloatSlider(value=0.25, max=1.0, ste…

# Note: the following visualization doesn't look very good.
It's only included here for completeness. 

In [21]:
import scipy.ndimage.morphology


def build2dLungMask(ct, mask_ndx, threshold_gcc=0.7):

    dense_mask = ct.hu_a[mask_ndx] > threshold_gcc

    denoise_mask = scipy.ndimage.morphology.binary_closing(dense_mask, iterations=2)

    tissue_mask = scipy.ndimage.morphology.binary_opening(denoise_mask, iterations=10)

    body_mask = scipy.ndimage.morphology.binary_fill_holes(tissue_mask)

    air_mask = scipy.ndimage.morphology.binary_fill_holes(body_mask & ~tissue_mask)

    lung_mask = scipy.ndimage.morphology.binary_dilation(air_mask, iterations=2)

    return air_mask, lung_mask, dense_mask, denoise_mask, tissue_mask, body_mask


def build3dLungMask(ct):
    air_mask, lung_mask, dense_mask, denoise_mask, tissue_mask, body_mask = (
        mask_list
    ) = [np.zeros_like(ct.hu_a, dtype=bool) for _ in range(6)]

    for mask_ndx in range(ct.hu_a.shape[0]):

        for i, mask_ary in enumerate(build2dLungMask(ct, mask_ndx)):

            mask_list[i][mask_ndx] = mask_ary

    return air_mask, lung_mask, dense_mask, denoise_mask, tissue_mask, body_mask

In [22]:
from p2ch10.dsets import getCt


ct = getCt(series_uid)


air_mask, lung_mask, dense_mask, denoise_mask, tissue_mask, body_mask = build3dLungMask(
    ct
)

C:\Users\LibraJiang\AppData\Local\Temp\ipykernel_21668\3567751507.py:8: DeprecationWarning: Please import `binary_closing` from the `scipy.ndimage` namespace; the `scipy.ndimage.morphology` namespace is deprecated and will be removed in SciPy 2.0.0.
  denoise_mask = scipy.ndimage.morphology.binary_closing(dense_mask, iterations=2)
C:\Users\LibraJiang\AppData\Local\Temp\ipykernel_21668\3567751507.py:10: DeprecationWarning: Please import `binary_opening` from the `scipy.ndimage` namespace; the `scipy.ndimage.morphology` namespace is deprecated and will be removed in SciPy 2.0.0.
  tissue_mask = scipy.ndimage.morphology.binary_opening(denoise_mask, iterations=10)
C:\Users\LibraJiang\AppData\Local\Temp\ipykernel_21668\3567751507.py:12: DeprecationWarning: Please import `binary_fill_holes` from the `scipy.ndimage` namespace; the `scipy.ndimage.morphology` namespace is deprecated and will be removed in SciPy 2.0.0.
  body_mask = scipy.ndimage.morphology.binary_fill_holes(tissue_mask)
C:\User

In [ ]:
bones = ct.hu_a * (ct.hu_a > 1.5)
lungs = ct.hu_a * air_mask
ipv.figure()
ipv.pylab.volshow(bones + lungs, level=[0.17, 0.17, 0.23], data_min=100, data_max=900)
ipv.show()

C:\Users\elis\Miniconda3\envs\book\lib\site-packages\ipyvolume\widgets.py:179: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  data_view = self.data_original[view]
C:\Users\elis\Miniconda3\envs\book\lib\site-packages\ipyvolume\utils.py:204: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  data = (data[slices1] + data[slices2])/2
C:\Users\elis\Miniconda3\envs\book\lib\site-packages\ipyvolume\serialize.py:81: RuntimeWarning: invalid value encountered in true_divide
  gradient = gradient / np.sqrt(gradient[0]**2 + gradient[1]**2 + gradient[2]**2)